# Generated by Django 5.0.6 on 2024-05-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_reply_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='date',
            new_name='created_at',
        ),
    ]
