# Generated by Django 5.0.6 on 2024-05-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_date_comment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='created_at',
        ),
    ]
