# Generated by Django 5.0.6 on 2024-05-22 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_contentpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='url',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='content_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='main.contentpage'),
        ),
    ]
