# Generated by Django 5.0.6 on 2024-05-22 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_bookmark_url_bookmark_content_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='slug',
        ),
    ]
