# Generated by Django 5.0.6 on 2024-05-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_bookmark_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
