# Generated by Django 5.0.6 on 2024-05-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_bookmark_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='content_page',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='url',
        ),
        migrations.AddField(
            model_name='contentpage',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
