# Generated by Django 5.0.6 on 2024-05-22 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_bookmark_content_page_remove_bookmark_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='content_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='main.contentpage'),
        ),
    ]
